Feature/faqs styling mobile
CruzHacks/cruzhacks-2023-website pull request #50
Opened 2022-11-02 20:05 UTC by xxzbuckxx

Problem
=======
- Add mobile styling for FAQs

Solution
========
- Added star icon and styled below 600px

Change Summary:
---------------
-

2022-11-03 00:06 UTC, Alperdec requested changes
Just one requested change with the text. The Cruzpoints info just needs a whitespace after the final comma and link.

This isn't necessary right now but, I think we should revisit this on a refactor and decouple the text from the `<QaBlurb>` component and insert them in a loop.

2022-11-03 00:06 UTC, Alperdec commented on src/views/Home/FAQs/index.view.tsx
> +            more information,
We need a space here after information,

2022-11-03 00:10 UTC, Alperdec commented
![image](https://user-images.githubusercontent.com/49699829/199625138-f198de73-adf7-4377-894c-505e790783f0.png)

Also it appears that the svg icon is having some issues. Is this because the sizing is relative to the container?

2022-11-03 00:11 UTC, Alperdec commented
Mobile view is spot on. One requested change and one buggy display

2022-11-03 00:26 UTC, xxzbuckxx commented
> 

I was thinking about this too

2022-11-03 01:43 UTC, Alperdec commented
I personally prefer it that way because it's easier to get lost in the sauce with too many items in a single component render. But like I said it's not a high priority currently

2022-11-06 01:43 UTC, sidhantas approved these changes
LGTM

2022-11-06 19:44 UTC, Alperdec approved these changes
Looks great

2022-11-06 19:45 UTC, merged