Chore/landing light mode
CruzHacks/cruzhacks-2023-website pull request #53
Opened 2022-11-08 02:18 UTC by sidhantas

Problem
=======
Created light mode for landing page

Solution
========
What I/we did to solve this problem
* 

Change Summary:
---------------
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------
* Insert any notes/issues, dependencies added or removed, or images

2022-11-08 17:28 UTC, xxzbuckxx approved these changes
The apply button should be filled in.

2022-11-09 01:30 UTC, Alperdec requested changes
Scaling/ position issues

2022-11-11 04:19 UTC, DevanOBoyle approved these changes
Looks good!

2022-11-11 06:45 UTC, Alperdec approved these changes

2022-11-11 06:45 UTC, merged